#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop

i=1

while [ $i -le 100 ]
do
	if [[ $((i%3)) == '0' && $((i%5)) == '0' ]]; then
		echo "FizzBuzz"
	elif [[ " == '0' ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
