#!/usr/bin/env bash
# This script is displaying content of the present working directory with a modified output

FILE=School
if [[ -e "$FILE" ]]; then
	    echo "$FILE file exists."
	    if [[ -f "$FILE" ]]; then
		    echo "$FILE is a regular file"
	    elif [[ -s "$FILE" ]]; then
		    echo "$FILE file is not empty"
	    else
		    echo "$FILE school file is empty"
	    fi
    else
	    echo "$FILE file does not exist"
fi

