#!/usr/bin/env bash
# This script is displaying "Clock"  using while loop

i=0
h=0

while [[ $h -le 12 && $i -le 60 ]]
do
	echo "$i"
	if [[ $((i%60)) == 0 ]]; then
		echo "Hour: $h"
		i=1
		((h++))
	elif [[ "$h" == 12 ]]; then
		echo "$i"
		((i++))
	else
		echo "$i"
		((i++))

	fi
done
